### PR TITLE
Warmaster revolution updates and developmental

### PR DESCRIPTION
**Pull request by noresjo**
Hello. 

This PR contains 2 thins really. 

- Updated pdfs of _approved_ Warmaster revolution as of 2022.
- A new "rule set" named warmaster revolution developmental with the latest changes as implemented by @Elenfir in his fork ( see PR #19). 

What do you think?

### CODE REVIEW

**Comment by Elenfir** [comment]
@noresjo Great idea adding it as it's own segment. I'll try and make time to update the magic items according to the new changes as well.

**Comment by noresjo** [comment]
@dsusco, any input on this(and related PR)?

**Comment by noresjo** [comment]
@dsusco , how are we going to proceed here? We really would like to get this "app" updated. Im open to to any solution.

**Comment by dsusco** [comment]
I'm finishing up parental leave next week and hoping to give the selector some attention after that.

**Comment by dsusco** [comment]
WMR Dev section added.

**Pull request closed without merging**
