### PR TITLE
Updated to adopted changes for WMRC 2022

### PR DESCRIPTION
**Pull request by Elenfir**
Added changes according to the WMRC 2022 document

### CODE REVIEW

**Comment by Elenfir** [comment]
As I read it these are the confirmed changes to the ruleset according to this page.

https://www.wm-revolution.com/articles/developmental.html

If someone can confirm that

**Comment by dsusco** [comment]
These are the developmental changes for 2022. I.e. what people will test for 2022 and be approved/rejected in 2023. They're a year early. :P

**Comment by Elenfir** [comment]
Ah I see. Well, I guess we'll wait a year ;).

**Comment by Elenfir** [comment]
Is it ok if I host this on a private server for our small community since all tournaments in Sweden this year uses the updated rules?

**Comment by Elenfir** [comment]
closing since all changes here are moved to another PR

**Pull request closed without merging**
